// ─────────────────────────────────────────────────────────────────────────────
// REAL × ORÇADO — quadro estático, tal como a folha do business plan
//
// É uma comparação ORÇADO vs FORECAST (não é realizado). Todas as linhas
// aparecem, pela ordem da folha, com os valores fixos do business plan.
//
// Origem do forecast por projeto:
//   Amadeu 07 e 7 Moinhos  → última coluna da folha "Evolucao Forecast"
//   Cinq Etoiles e Paço D'arcos → coluna "Real" da folha "Real x Orçado",
//        que nesses modelos é o resultado projetado do projeto inteiro
//   Maria Pia → ainda sem forecast (a folha "Evolucao Forecast" do ficheiro
//        está com os números do 7 Moinhos, por copiar)
//
// Tipos de linha: item | subtotal (soma os filhos quando falta valor) |
//                 resultado | espaco (linha em branco, como na folha)
// ─────────────────────────────────────────────────────────────────────────────

export const MODELO_REAL_ORCADO = {
  favcloset: {
    projeto: "Amadeu 07", familia: "lpx", fonteForecast: "forecast 10.09",
    linhas: [
      { tipo: "subtotal", rotulo: "VENDAS LÍQUIDAS", filhos: ["Vendas", "Comissão"], orcado: 3412461.08, forecast: 3755676.32 },
      { tipo: "item", rotulo: "Vendas", orcado: 3636080.0, forecast: 3994394.72 },
      { tipo: "item", rotulo: "Comissão", orcado: -223618.92, forecast: -238718.4 },
      { tipo: "subtotal", rotulo: "DESPESAS TOTAIS", filhos: ["Terreno", "Impostos e taxas", "Encargos financeiros", "Legais", "Marketing", "Projetos", "Obra", "Administrativos", "Fiscalização", "Fee Gestão", "Juros", "Ajuste"], orcado: -2645638.08, forecast: -2763716.96 },
      { tipo: "item", rotulo: "Terreno", orcado: -993232.0, forecast: -945650.0 },
      { tipo: "item", rotulo: "Impostos e taxas", orcado: -17000.0, forecast: -29992.45 },
      { tipo: "item", rotulo: "Encargos financeiros", orcado: -16632.0, forecast: -32911.87 },
      { tipo: "item", rotulo: "Legais", orcado: -6765.0, forecast: -7556.38 },
      { tipo: "item", rotulo: "Marketing", orcado: -30750.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Projetos", orcado: -30769.68, forecast: -95221.68 },
      { tipo: "item", rotulo: "Obra", orcado: -1277293.96, forecast: -1378000.0 },
      { tipo: "item", rotulo: "Administrativos", orcado: -7692.42, forecast: -13160.71 },
      { tipo: "item", rotulo: "Fiscalização", orcado: -46740.0, forecast: -34194.0 },
      { tipo: "item", rotulo: "Fee Gestão", orcado: -125920.02, forecast: -125919.93 },
      { tipo: "item", rotulo: "Juros", orcado: -92843.0, forecast: -101109.94 },
      { tipo: "item", rotulo: "Ajuste", orcado: 0.0, forecast: null },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Lucro tributável", orcado: 766823.0, forecast: 991959.36 },
      { tipo: "resultado", rotulo: "Success Fee", orcado: -185190.39, forecast: -185479.09 },
      { tipo: "resultado", rotulo: "IRC", orcado: -130867.34, forecast: -163828.46 },
      { tipo: "resultado", rotulo: "Lucro líquido", orcado: 450765.27, forecast: 642651.82 },
    ],
  },
  simplify: {
    projeto: "Alto dos 7 Moinhos", familia: "lpx", fonteForecast: "forecast 6.07",
    linhas: [
      { tipo: "subtotal", rotulo: "VENDAS LÍQUIDAS", filhos: ["Vendas", "Comissão"], orcado: 2462624.0, forecast: null },
      { tipo: "item", rotulo: "Vendas", orcado: 2624000.0, forecast: 2848960.89 },
      { tipo: "item", rotulo: "Comissão", orcado: -161376.0, forecast: -145693.26 },
      { tipo: "subtotal", rotulo: "DESPESAS TOTAIS", filhos: ["Terreno", "Impostos e taxas", "Encargos financeiros", "Legais", "Marketing", "Projetos", "Obra", "Administrativos", "Fiscalização", "Fee Gestão", "Juros", "Ajuste"], orcado: -1857852.5, forecast: null },
      { tipo: "item", rotulo: "Terreno", orcado: -585500.0, forecast: -585500.0 },
      { tipo: "item", rotulo: "Impostos e taxas", orcado: -64320.0, forecast: -44841.04 },
      { tipo: "item", rotulo: "Encargos financeiros", orcado: -12248.0, forecast: null },
      { tipo: "item", rotulo: "Legais", orcado: -11070.0, forecast: -8298.57 },
      { tipo: "item", rotulo: "Marketing", orcado: -9840.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Projetos", orcado: -35625.72, forecast: -44462.42 },
      { tipo: "item", rotulo: "Obra", orcado: -996148.78, forecast: -1218999.96 },
      { tipo: "item", rotulo: "Administrativos", orcado: 0.0, forecast: -4220.69 },
      { tipo: "item", rotulo: "Fiscalização", orcado: -19680.0, forecast: -35369.81 },
      { tipo: "item", rotulo: "Fee Gestão", orcado: -79950.0, forecast: -79947.13 },
      { tipo: "item", rotulo: "Juros", orcado: -43470.0, forecast: -37823.59 },
      { tipo: "item", rotulo: "Ajuste", orcado: 0.0, forecast: null },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Lucro tributável", orcado: 604771.5, forecast: 616269.78 },
      { tipo: "resultado", rotulo: "Success Fee", orcado: -162920.0, forecast: -118008.31 },
      { tipo: "resultado", rotulo: "IRC", orcado: -88370.3, forecast: -100643.6 },
      { tipo: "resultado", rotulo: "Lucro líquido", orcado: 353481.2, forecast: 397617.87 },
    ],
  },
  genero: {
    projeto: "Maria Pia", familia: "lpx", fonteForecast: null,
    linhas: [
      { tipo: "subtotal", rotulo: "VENDAS LÍQUIDAS", filhos: ["Vendas", "Comissão"], orcado: 3817462.0, forecast: null },
      { tipo: "item", rotulo: "Vendas", orcado: 4015000.0, forecast: null },
      { tipo: "item", rotulo: "Comissão", orcado: -197538.0, forecast: null },
      { tipo: "subtotal", rotulo: "DESPESAS TOTAIS", filhos: ["Terreno", "Impostos e taxas", "Encargos financeiros", "Legais", "Marketing", "Projetos", "Obra", "Administrativos", "Fiscalização", "Fee Gestão", "Juros", "Ajuste"], orcado: -2612084.69, forecast: null },
      { tipo: "item", rotulo: "Terreno", orcado: -1450000.0, forecast: null },
      { tipo: "item", rotulo: "Impostos e taxas", orcado: -22100.0, forecast: null },
      { tipo: "item", rotulo: "Encargos financeiros", orcado: -13563.87, forecast: null },
      { tipo: "item", rotulo: "Legais", orcado: 0.0, forecast: null },
      { tipo: "item", rotulo: "Marketing", orcado: -12045.0, forecast: null },
      { tipo: "item", rotulo: "Projetos", orcado: -29326.64, forecast: null },
      { tipo: "item", rotulo: "Obra", orcado: -1043581.08, forecast: null },
      { tipo: "item", rotulo: "Administrativos", orcado: 0.0, forecast: null },
      { tipo: "item", rotulo: "Fiscalização", orcado: 0.0, forecast: null },
      { tipo: "item", rotulo: "Fee Gestão", orcado: 0.0, forecast: null },
      { tipo: "item", rotulo: "Juros", orcado: -41468.11, forecast: null },
      { tipo: "item", rotulo: "Ajuste", orcado: 0.0, forecast: null },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Lucro tributável", orcado: 1205377.31, forecast: null },
      { tipo: "resultado", rotulo: "Success Fee", orcado: -241075.46, forecast: null },
      { tipo: "resultado", rotulo: "IRC", orcado: -192860.37, forecast: null },
      { tipo: "resultado", rotulo: "Lucro líquido", orcado: 771441.48, forecast: null },
    ],
  },
  adseq: {
    projeto: "Cinq Etoiles", familia: "hdg", fonteForecast: "coluna \"Real\" do BP",
    linhas: [
      { tipo: "resultado", rotulo: "SALDO INICIAL", orcado: 0.0, forecast: 0.0 },
      { tipo: "espaco" },
      { tipo: "item", rotulo: "Vendas", orcado: 4654700.0, forecast: 5298999.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Licenças_e_Relacionados", filhos: ["Projetos de Loteamento", "Projetos de Arquitetura e Especialidades", "Taxas e emolumentos", "Advogados - Licenças", "Outros custos de Estruturação"], orcado: -35750.0, forecast: -31451.53 },
      { tipo: "item", rotulo: "Projetos de Loteamento", orcado: 0.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Projetos de Arquitetura e Especialidades", orcado: -24600.0, forecast: -26771.0 },
      { tipo: "item", rotulo: "Taxas e emolumentos", orcado: -5000.0, forecast: -2680.53 },
      { tipo: "item", rotulo: "Advogados - Licenças", orcado: -6150.0, forecast: -2000.0 },
      { tipo: "item", rotulo: "Outros custos de Estruturação", orcado: 0.0, forecast: 0.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Aquisição_de_Terreno", filhos: ["Aquisição Terreno", "IMT", "Imposto Selo", "Notário", "Registos", "Outros"], orcado: -1969600.0, forecast: -1780574.63 },
      { tipo: "item", rotulo: "Aquisição Terreno", orcado: -1950000.0, forecast: -1755000.0 },
      { tipo: "item", rotulo: "IMT", orcado: 0.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Imposto Selo", orcado: -15600.0, forecast: -15600.0 },
      { tipo: "item", rotulo: "Notário", orcado: -3000.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Registos", orcado: -1000.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Outros", orcado: 0.0, forecast: -9974.63 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Obras", filhos: ["Demolição e Preparação", "Gastos com Obras", "Taxas (Obras)", "Buffer/Outros"], orcado: -995739.89, forecast: -1427936.03 },
      { tipo: "item", rotulo: "Demolição e Preparação", orcado: 0.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Gastos com Obras", orcado: -948323.7, forecast: -1427313.9 },
      { tipo: "item", rotulo: "Taxas (Obras)", orcado: 0.0, forecast: -376.32 },
      { tipo: "item", rotulo: "Buffer/Outros", orcado: -47416.19, forecast: -245.81 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Soft_Costs", filhos: ["Taxas de estruturação", "Taxa de Gestão", "Seguros diversos", "Seguro de Obra", "Fiscalização", "TOC (Contabilidade)", "ROC (Auditoria)", "Marketing e propraganda", "Comissão s/Vendas", "Outros - Comissões Bancárias", "Setup Costs", "Outros - Diversos", "Outros - Diversos SC", "Adiantamentos"], orcado: -425205.8, forecast: -451076.56 },
      { tipo: "item", rotulo: "Taxas de estruturação", orcado: null, forecast: 0.0 },
      { tipo: "item", rotulo: "Taxa de Gestão", orcado: -121770.0, forecast: -74416.0 },
      { tipo: "item", rotulo: "Seguros diversos", orcado: null, forecast: -588.33 },
      { tipo: "item", rotulo: "Seguro de Obra", orcado: 0.0, forecast: -16808.37 },
      { tipo: "item", rotulo: "Fiscalização", orcado: 0.0, forecast: -22847.25 },
      { tipo: "item", rotulo: "TOC (Contabilidade)", orcado: -5535.0, forecast: -5387.4 },
      { tipo: "item", rotulo: "ROC (Auditoria)", orcado: null, forecast: 0.0 },
      { tipo: "item", rotulo: "Marketing e propraganda", orcado: -11636.75, forecast: -8187.06 },
      { tipo: "item", rotulo: "Comissão s/Vendas", orcado: -286264.05, forecast: -297844.44 },
      { tipo: "item", rotulo: "Outros - Comissões Bancárias", orcado: null, forecast: -3532.44 },
      { tipo: "item", rotulo: "Setup Costs", orcado: null, forecast: -9131.88 },
      { tipo: "item", rotulo: "Outros - Diversos SC", orcado: null, forecast: -12333.39 },
      { tipo: "item", rotulo: "Adiantamentos", orcado: null, forecast: 0.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Financiamento", filhos: ["Outflow - Juros", "Outflow - Taxas e comissões"], orcado: -18255.23, forecast: -152829.17 },
      { tipo: "item", rotulo: "Outflow - Juros", orcado: -18255.23, forecast: -98964.1 },
      { tipo: "item", rotulo: "Outflow - Taxas e comissões", orcado: 0.0, forecast: -53865.07 },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Lucro bruto", orcado: 1210149.08, forecast: 1455131.08 },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Imposto s/ lucro", orcado: null, forecast: -310853.18 },
      { tipo: "resultado", rotulo: "Lucro líquido (net of tax)", orcado: null, forecast: 1144277.9 },
    ],
  },
  infinite: {
    projeto: "Paço D'arcos", familia: "hdg", fonteForecast: "coluna \"Real\" do BP",
    linhas: [
      { tipo: "resultado", rotulo: "SALDO INICIAL", orcado: 0.0, forecast: 0.0 },
      { tipo: "espaco" },
      { tipo: "item", rotulo: "Vendas", orcado: 9784920.0, forecast: 11778000.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Licenças_e_Relacionados", filhos: ["Projetos de Loteamento", "Projetos de Arquitetura e Especialidades", "Taxas e emolumentos", "Advogados - Licenças", "Outros custos de Estruturação"], orcado: -49200.0, forecast: -154406.47 },
      { tipo: "item", rotulo: "Projetos de Loteamento", orcado: 0.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Projetos de Arquitetura e Especialidades", orcado: -36900.0, forecast: -139598.9 },
      { tipo: "item", rotulo: "Taxas e emolumentos", orcado: -12300.0, forecast: -12807.57 },
      { tipo: "item", rotulo: "Advogados - Licenças", orcado: 0.0, forecast: -2000.0 },
      { tipo: "item", rotulo: "Outros custos de Estruturação", orcado: 0.0, forecast: 0.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Aquisição_de_Terreno", filhos: ["Aquisição Terreno", "IMT", "Imposto Selo", "Notário", "Registos", "Outros"], orcado: -2278300.0, forecast: -2244567.88 },
      { tipo: "item", rotulo: "Aquisição Terreno", orcado: -2100000.0, forecast: -2089787.41 },
      { tipo: "item", rotulo: "IMT", orcado: -157500.0, forecast: -136500.0 },
      { tipo: "item", rotulo: "Imposto Selo", orcado: -16800.0, forecast: -16800.0 },
      { tipo: "item", rotulo: "Notário", orcado: -4000.0, forecast: -1480.47 },
      { tipo: "item", rotulo: "Registos", orcado: 0.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Outros", orcado: 0.0, forecast: 0.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Obras", filhos: ["Demolição e Preparação", "Gastos com Obras", "Taxas (Obras)", "Buffer/Outros"], orcado: -4574028.06, forecast: -4635470.35 },
      { tipo: "item", rotulo: "Demolição e Preparação", orcado: 0.0, forecast: -60344.72 },
      { tipo: "item", rotulo: "Gastos com Obras", orcado: -4356217.2, forecast: -4567981.2 },
      { tipo: "item", rotulo: "Taxas (Obras)", orcado: 0.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Buffer/Outros", orcado: -217810.86, forecast: -7144.43 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Soft_Costs", filhos: ["Taxas de estruturação", "Taxa de Gestão", "Seguros diversos", "Seguro de Obra", "Fiscalização", "TOC (Contabilidade)", "ROC (Auditoria)", "Marketing e propraganda", "Comissão s/Vendas", "Outros - Comissões Bancárias", "Setup Costs", "Outros - Diversos", "Outros - Diversos SC", "Adiantamentos"], orcado: -874249.68, forecast: -980237.4 },
      { tipo: "item", rotulo: "Taxas de estruturação", orcado: 0.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Taxa de Gestão", orcado: -216480.0, forecast: -226320.0 },
      { tipo: "item", rotulo: "Seguros diversos", orcado: 0.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Seguro de Obra", orcado: 0.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Fiscalização", orcado: 0.0, forecast: -11100.75 },
      { tipo: "item", rotulo: "TOC (Contabilidade)", orcado: -7072.5, forecast: -4870.9 },
      { tipo: "item", rotulo: "ROC (Auditoria)", orcado: 0.0, forecast: 0.0 },
      { tipo: "item", rotulo: "Marketing e propraganda", orcado: -48924.6, forecast: 0.0 },
      { tipo: "item", rotulo: "Comissão s/Vendas", orcado: -601772.58, forecast: -724347.0 },
      { tipo: "item", rotulo: "Outros - Comissões Bancárias", orcado: 0.0, forecast: -213.46 },
      { tipo: "item", rotulo: "Setup Costs", orcado: 0.0, forecast: -6949.51 },
      { tipo: "item", rotulo: "Outros - Diversos", orcado: 0.0, forecast: -6435.78 },
      { tipo: "item", rotulo: "Adiantamentos", orcado: 0.0, forecast: 0.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Financiamento", filhos: ["Outflow - Juros", "Outflow - Taxas e comissões"], orcado: -172279.24, forecast: -241577.35 },
      { tipo: "item", rotulo: "Outflow - Juros", orcado: -172279.24, forecast: -166263.35 },
      { tipo: "item", rotulo: "Outflow - Taxas e comissões", orcado: 0.0, forecast: -75314.0 },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Lucro bruto", orcado: 1836863.02, forecast: 3521740.55 },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "IRC", orcado: -357439.86, forecast: -623556.79 },
      { tipo: "resultado", rotulo: "Success Fee", orcado: -248241.4, forecast: -555150.84 },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Lucro líquido", orcado: 1231181.76, forecast: 2343032.93 },
    ],
  },
};

export default MODELO_REAL_ORCADO;