// ─────────────────────────────────────────────────────────────────────────────
// MODELO DO REAL × ORÇADO — replica a folha "Real x Orçado" de cada projeto
//
// A estrutura (ordem das linhas, subtotais, linhas em branco) e a coluna
// ORÇADO vêm do business plan e são fixas.
// O REALIZADO flutua: é calculado ao vivo a partir do ERP.
//
// Tipos de linha:
//   item      — categoria com realizado vindo dos movimentos do ERP
//   subtotal  — soma dos `filhos`; realizado também somado dos filhos
//   resultado — linha de resultado do BP (lucro, impostos); `real_bp` é o valor
//               que a folha calculava, usado só quando não dá para derivar
//   espaco    — linha em branco, para o quadro ficar igual à folha
// ─────────────────────────────────────────────────────────────────────────────

export const MODELO_REAL_ORCADO = {
  favcloset: {
    projeto: "Amadeu 07", familia: "lpx",
    linhas: [
      { tipo: "subtotal", rotulo: "VENDAS LÍQUIDAS", filhos: ["Vendas", "Comissão"], orcado: 3412461.08 },
      { tipo: "item", rotulo: "Vendas", orcado: 3636080.0 },
      { tipo: "item", rotulo: "Comissão", orcado: -223618.92 },
      { tipo: "subtotal", rotulo: "DESPESAS TOTAIS", filhos: ["Terreno", "Impostos e taxas", "Encargos financeiros", "Legais", "Marketing", "Projetos", "Obra", "Administrativos", "Fiscalização", "Fee Gestão", "Juros", "Ajuste"], orcado: -2645638.08 },
      { tipo: "item", rotulo: "Terreno", orcado: -993232.0 },
      { tipo: "item", rotulo: "Impostos e taxas", orcado: -17000.0 },
      { tipo: "item", rotulo: "Encargos financeiros", orcado: -16632.0 },
      { tipo: "item", rotulo: "Legais", orcado: -6765.0 },
      { tipo: "item", rotulo: "Marketing", orcado: -30750.0 },
      { tipo: "item", rotulo: "Projetos", orcado: -30769.68 },
      { tipo: "item", rotulo: "Obra", orcado: -1277293.96 },
      { tipo: "item", rotulo: "Administrativos", orcado: -7692.42 },
      { tipo: "item", rotulo: "Fiscalização", orcado: -46740.0 },
      { tipo: "item", rotulo: "Fee Gestão", orcado: -125920.02 },
      { tipo: "item", rotulo: "Juros", orcado: -92843.0 },
      { tipo: "item", rotulo: "Ajuste", orcado: 0.0 },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Lucro tributável", orcado: 766823.0, real_bp: null },
      { tipo: "resultado", rotulo: "Success Fee", orcado: -185190.39, real_bp: null },
      { tipo: "resultado", rotulo: "IRC", orcado: -130867.34, real_bp: null },
      { tipo: "resultado", rotulo: "Lucro líquido", orcado: 450765.27, real_bp: null },
    ],
  },
  simplify: {
    projeto: "Alto dos 7 Moinhos", familia: "lpx",
    linhas: [
      { tipo: "subtotal", rotulo: "VENDAS LÍQUIDAS", filhos: ["Vendas", "Comissão"], orcado: 2462624.0 },
      { tipo: "item", rotulo: "Vendas", orcado: 2624000.0 },
      { tipo: "item", rotulo: "Comissão", orcado: -161376.0 },
      { tipo: "subtotal", rotulo: "DESPESAS TOTAIS", filhos: ["Terreno", "Impostos e taxas", "Encargos financeiros", "Legais", "Marketing", "Projetos", "Obra", "Administrativos", "Fiscalização", "Fee Gestão", "Juros", "Ajuste"], orcado: -1857852.5 },
      { tipo: "item", rotulo: "Terreno", orcado: -585500.0 },
      { tipo: "item", rotulo: "Impostos e taxas", orcado: -64320.0 },
      { tipo: "item", rotulo: "Encargos financeiros", orcado: -12248.0 },
      { tipo: "item", rotulo: "Legais", orcado: -11070.0 },
      { tipo: "item", rotulo: "Marketing", orcado: -9840.0 },
      { tipo: "item", rotulo: "Projetos", orcado: -35625.72 },
      { tipo: "item", rotulo: "Obra", orcado: -996148.78 },
      { tipo: "item", rotulo: "Administrativos", orcado: 0.0 },
      { tipo: "item", rotulo: "Fiscalização", orcado: -19680.0 },
      { tipo: "item", rotulo: "Fee Gestão", orcado: -79950.0 },
      { tipo: "item", rotulo: "Juros", orcado: -43470.0 },
      { tipo: "item", rotulo: "Ajuste", orcado: 0.0 },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Lucro tributável", orcado: 604771.5, real_bp: null },
      { tipo: "resultado", rotulo: "Success Fee", orcado: -162920.0, real_bp: null },
      { tipo: "resultado", rotulo: "IRC", orcado: -88370.3, real_bp: null },
      { tipo: "resultado", rotulo: "Lucro líquido", orcado: 353481.2, real_bp: null },
    ],
  },
  genero: {
    projeto: "Maria Pia", familia: "lpx",
    linhas: [
      { tipo: "subtotal", rotulo: "VENDAS LÍQUIDAS", filhos: ["Vendas", "Comissão"], orcado: 3817462.0 },
      { tipo: "item", rotulo: "Vendas", orcado: 4015000.0 },
      { tipo: "item", rotulo: "Comissão", orcado: -197538.0 },
      { tipo: "subtotal", rotulo: "DESPESAS TOTAIS", filhos: ["Terreno", "Impostos e taxas", "Encargos financeiros", "Legais", "Marketing", "Projetos", "Obra", "Administrativos", "Fiscalização", "Fee Gestão", "Juros", "Ajuste"], orcado: -2612084.69 },
      { tipo: "item", rotulo: "Terreno", orcado: -1450000.0 },
      { tipo: "item", rotulo: "Impostos e taxas", orcado: -22100.0 },
      { tipo: "item", rotulo: "Encargos financeiros", orcado: -13563.87 },
      { tipo: "item", rotulo: "Legais", orcado: 0.0 },
      { tipo: "item", rotulo: "Marketing", orcado: -12045.0 },
      { tipo: "item", rotulo: "Projetos", orcado: -29326.64 },
      { tipo: "item", rotulo: "Obra", orcado: -1043581.08 },
      { tipo: "item", rotulo: "Administrativos", orcado: 0.0 },
      { tipo: "item", rotulo: "Fiscalização", orcado: 0.0 },
      { tipo: "item", rotulo: "Fee Gestão", orcado: 0.0 },
      { tipo: "item", rotulo: "Juros", orcado: -41468.11 },
      { tipo: "item", rotulo: "Ajuste", orcado: 0.0 },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Lucro tributável", orcado: 1205377.31, real_bp: null },
      { tipo: "resultado", rotulo: "Success Fee", orcado: -241075.46, real_bp: null },
      { tipo: "resultado", rotulo: "IRC", orcado: -192860.37, real_bp: null },
      { tipo: "resultado", rotulo: "Lucro líquido", orcado: 771441.48, real_bp: null },
    ],
  },
  adseq: {
    projeto: "Cinq Etoiles", familia: "hdg",
    linhas: [
      { tipo: "resultado", rotulo: "SALDO INICIAL", orcado: 0.0, real_bp: 0.0 },
      { tipo: "espaco" },
      { tipo: "item", rotulo: "Vendas", orcado: 4654700.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Licenças_e_Relacionados", filhos: ["Projetos de Loteamento", "Projetos de Arquitetura e Especialidades", "Taxas e emolumentos", "Advogados - Licenças", "Outros custos de Estruturação"], orcado: -35750.0 },
      { tipo: "item", rotulo: "Projetos de Loteamento", orcado: 0.0 },
      { tipo: "item", rotulo: "Projetos de Arquitetura e Especialidades", orcado: -24600.0 },
      { tipo: "item", rotulo: "Taxas e emolumentos", orcado: -5000.0 },
      { tipo: "item", rotulo: "Advogados - Licenças", orcado: -6150.0 },
      { tipo: "item", rotulo: "Outros custos de Estruturação", orcado: 0.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Aquisição_de_Terreno", filhos: ["Aquisição Terreno", "IMT", "Imposto Selo", "Notário", "Registos", "Outros"], orcado: -1969600.0 },
      { tipo: "item", rotulo: "Aquisição Terreno", orcado: -1950000.0 },
      { tipo: "item", rotulo: "IMT", orcado: 0.0 },
      { tipo: "item", rotulo: "Imposto Selo", orcado: -15600.0 },
      { tipo: "item", rotulo: "Notário", orcado: -3000.0 },
      { tipo: "item", rotulo: "Registos", orcado: -1000.0 },
      { tipo: "item", rotulo: "Outros", orcado: 0.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Obras", filhos: ["Demolição e Preparação", "Gastos com Obras", "Taxas (Obras)", "Buffer/Outros"], orcado: -995739.89 },
      { tipo: "item", rotulo: "Demolição e Preparação", orcado: 0.0 },
      { tipo: "item", rotulo: "Gastos com Obras", orcado: -948323.7 },
      { tipo: "item", rotulo: "Taxas (Obras)", orcado: 0.0 },
      { tipo: "item", rotulo: "Buffer/Outros", orcado: -47416.19 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Soft_Costs", filhos: ["Taxas de estruturação", "Taxa de Gestão", "Seguros diversos", "Seguro de Obra", "Fiscalização", "TOC (Contabilidade)", "ROC (Auditoria)", "Marketing e propraganda", "Comissão s/Vendas", "Outros - Comissões Bancárias", "Setup Costs", "Outros - Diversos", "Outros - Diversos SC", "Adiantamentos"], orcado: -425205.8 },
      { tipo: "item", rotulo: "Taxas de estruturação", orcado: null },
      { tipo: "item", rotulo: "Taxa de Gestão", orcado: -121770.0 },
      { tipo: "item", rotulo: "Seguros diversos", orcado: null },
      { tipo: "item", rotulo: "Seguro de Obra", orcado: 0.0 },
      { tipo: "item", rotulo: "Fiscalização", orcado: 0.0 },
      { tipo: "item", rotulo: "TOC (Contabilidade)", orcado: -5535.0 },
      { tipo: "item", rotulo: "ROC (Auditoria)", orcado: null },
      { tipo: "item", rotulo: "Marketing e propraganda", orcado: -11636.75 },
      { tipo: "item", rotulo: "Comissão s/Vendas", orcado: -286264.05 },
      { tipo: "item", rotulo: "Outros - Comissões Bancárias", orcado: null },
      { tipo: "item", rotulo: "Setup Costs", orcado: null },
      { tipo: "item", rotulo: "Outros - Diversos SC", orcado: null },
      { tipo: "item", rotulo: "Adiantamentos", orcado: null },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Financiamento", filhos: ["Outflow - Juros", "Outflow - Taxas e comissões"], orcado: -18255.23 },
      { tipo: "item", rotulo: "Outflow - Juros", orcado: -18255.23 },
      { tipo: "item", rotulo: "Outflow - Taxas e comissões", orcado: 0.0 },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Lucro bruto", orcado: 1210149.08, real_bp: 1455131.08 },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Imposto s/ lucro", orcado: null, real_bp: -310853.18 },
      { tipo: "resultado", rotulo: "Lucro líquido (net of tax)", orcado: null, real_bp: 1144277.9 },
    ],
  },
  infinite: {
    projeto: "Paço D'arcos", familia: "hdg",
    linhas: [
      { tipo: "resultado", rotulo: "SALDO INICIAL", orcado: 0.0, real_bp: 0.0 },
      { tipo: "espaco" },
      { tipo: "item", rotulo: "Vendas", orcado: 9784920.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Licenças_e_Relacionados", filhos: ["Projetos de Loteamento", "Projetos de Arquitetura e Especialidades", "Taxas e emolumentos", "Advogados - Licenças", "Outros custos de Estruturação"], orcado: -49200.0 },
      { tipo: "item", rotulo: "Projetos de Loteamento", orcado: 0.0 },
      { tipo: "item", rotulo: "Projetos de Arquitetura e Especialidades", orcado: -36900.0 },
      { tipo: "item", rotulo: "Taxas e emolumentos", orcado: -12300.0 },
      { tipo: "item", rotulo: "Advogados - Licenças", orcado: 0.0 },
      { tipo: "item", rotulo: "Outros custos de Estruturação", orcado: 0.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Aquisição_de_Terreno", filhos: ["Aquisição Terreno", "IMT", "Imposto Selo", "Notário", "Registos", "Outros"], orcado: -2278300.0 },
      { tipo: "item", rotulo: "Aquisição Terreno", orcado: -2100000.0 },
      { tipo: "item", rotulo: "IMT", orcado: -157500.0 },
      { tipo: "item", rotulo: "Imposto Selo", orcado: -16800.0 },
      { tipo: "item", rotulo: "Notário", orcado: -4000.0 },
      { tipo: "item", rotulo: "Registos", orcado: 0.0 },
      { tipo: "item", rotulo: "Outros", orcado: 0.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Obras", filhos: ["Demolição e Preparação", "Gastos com Obras", "Taxas (Obras)", "Buffer/Outros"], orcado: -4574028.06 },
      { tipo: "item", rotulo: "Demolição e Preparação", orcado: 0.0 },
      { tipo: "item", rotulo: "Gastos com Obras", orcado: -4356217.2 },
      { tipo: "item", rotulo: "Taxas (Obras)", orcado: 0.0 },
      { tipo: "item", rotulo: "Buffer/Outros", orcado: -217810.86 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Soft_Costs", filhos: ["Taxas de estruturação", "Taxa de Gestão", "Seguros diversos", "Seguro de Obra", "Fiscalização", "TOC (Contabilidade)", "ROC (Auditoria)", "Marketing e propraganda", "Comissão s/Vendas", "Outros - Comissões Bancárias", "Setup Costs", "Outros - Diversos", "Outros - Diversos SC", "Adiantamentos"], orcado: -874249.68 },
      { tipo: "item", rotulo: "Taxas de estruturação", orcado: 0.0 },
      { tipo: "item", rotulo: "Taxa de Gestão", orcado: -216480.0 },
      { tipo: "item", rotulo: "Seguros diversos", orcado: 0.0 },
      { tipo: "item", rotulo: "Seguro de Obra", orcado: 0.0 },
      { tipo: "item", rotulo: "Fiscalização", orcado: 0.0 },
      { tipo: "item", rotulo: "TOC (Contabilidade)", orcado: -7072.5 },
      { tipo: "item", rotulo: "ROC (Auditoria)", orcado: 0.0 },
      { tipo: "item", rotulo: "Marketing e propraganda", orcado: -48924.6 },
      { tipo: "item", rotulo: "Comissão s/Vendas", orcado: -601772.58 },
      { tipo: "item", rotulo: "Outros - Comissões Bancárias", orcado: 0.0 },
      { tipo: "item", rotulo: "Setup Costs", orcado: 0.0 },
      { tipo: "item", rotulo: "Outros - Diversos", orcado: 0.0 },
      { tipo: "item", rotulo: "Adiantamentos", orcado: 0.0 },
      { tipo: "espaco" },
      { tipo: "subtotal", rotulo: "Financiamento", filhos: ["Outflow - Juros", "Outflow - Taxas e comissões"], orcado: -172279.24 },
      { tipo: "item", rotulo: "Outflow - Juros", orcado: -172279.24 },
      { tipo: "item", rotulo: "Outflow - Taxas e comissões", orcado: 0.0 },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Lucro bruto", orcado: 1836863.02, real_bp: 3521740.55 },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "IRC", orcado: -357439.86, real_bp: -623556.79 },
      { tipo: "resultado", rotulo: "Success Fee", orcado: -248241.4, real_bp: -555150.84 },
      { tipo: "espaco" },
      { tipo: "resultado", rotulo: "Lucro líquido", orcado: 1231181.76, real_bp: 2343032.93 },
    ],
  },
};

export default MODELO_REAL_ORCADO;